
var dict = {
    "albue": "elbow, to elbow",
    "altså": "accordingly, really",
    "bonde": "farmer",
    "bred": "shore, broad, wide",
    "brede ud": "to spread out, to unfold",
    "brede": "to spread",
    "bunke": "pile",
    "byde": "to offer",
    "byld": "abscess",
    "bøje": "to bend",
    "duft": "fragrance",
    "dufte": "to smell",
    "ellers": "otherwise",
    "endnu": "still, yet",
    "ensom": "lonely",
    "forelskelse": "infatuation",
    "forfærdelige": "terrible",
    "forklare": "to explain",
    "forsigtigt": "carefully",
    "forskrækket": "frightened",
    "forsvandt": "disappeared",
    "forsørge": "to support, to provide for",
    "fremmed": "foreign, strange",
    "fugtig":"humid",
    "gemme": "to save, to hide",
    "glæde": "joy",
    "gribe": "to grip, to catch",
    "græsse": "to graze",
    "gå i gang": "to start, to begin",
    "gårdsplads": "courtyard",
    "handlende": "tradesman",
    "hellere": "rather, sooner",
    "helskindet": "without a scratch",
    "helst": "preferably, rather",
    "helt": "hero, completely",
    "hidsig": "hot tempered",
    "hoste": "cough",
    "hvad som helst": "anything",
    "hvem som helst": "anybody",
    "hvilken som helst": "any",
    "hviske": "to whisper",
    "hvor som helst": "anywhere, wherever",
    "håndtryk": "handshake",
    "håndværk": "profession",
    "høj": "hill",
    "i det lange løb": "in the long run",
    "ifølge": "according to",
    "ildrød": "fiery red",
    "indbyde": "to invite",
    "indbydelse": "invitation",
    "indbygger": "inhabitant",
    "inden for rækkevidde": "within reach",
    "inden for": "within",
    "inden i": "inside",
    "inden under": "underneath",
    "inden": "before",
    "indenom": "along the inside",
    "indenrigs": "domestic",
    "indføre":"to introduce",
    "indre": "interior, inner",
    "indrette": "to organize",
    "ingen som helst": "not at all",
    "intet som helst": "nothing whatsoever",
    "klem": "hug",
    "klippe": "cliff",
    "komme væk": "to get away",
    "kopper": "smallpox",
    "kølig": "cool",
    "landbrug": "agriculture, farming",
    "landskab": "landscape",
    "langt fra": "a long way from, far away from",
    "langt ind i": "far into",
    "langt om længe": "at long last",
    "langt væk": "far away",
    "langtfra": "not at all, far from",
    "langvejs": "a long way",
    "lighed": "equality",
    "læs": "load",
    "løfte": "to promise, to lift",
    "medfølelse": "compassion",
    "miste": "to lose",
    "mon": "I wonder",
    "må hellere": "better",
    "nikke": "to nod",
    "når som helst": "whenever, anytime",
    "nødvendigt": "necessary",
    "ophæve":"to repeal",
    "opmærksomt": "carefully",
    "oprør": "rebellion",
    "oven": "on top",
    "overalt": "everywhere",
    "overfalde": "to assault",
    "overraskede": "surprised",
    "overskrift": "title",
    "pege":"to point",
    "piske": "to whip",
    "plejebarn": "foster child",
    "rask": "healthy",
    "regne med": "count on, depend on",
    "regne": "to calculate",
    "regnskab": "account",
    "rejsende": "traveller",
    "ryg": "back",
    "rygte": "rumor",
    "rynke": "to frown, wrinkle",
    "ryste": "to shake, to upset",
    "række ud": "to reach out",
    "røver": "robber",
    "skab": "cupboard, closet",
    "skomager": "cobbler",
    "skridt": "step",
    "skrædderværksted": "tailor workshop",
    "skygge": "shadow",
    "skynde": "to rush",
    "skælde": "to scold",
    "slags": "type",
    "slette": "plain, field, to delete, to erase",
    "slippe": "to release",
    "smed": "smith",
    "smide": "to throw",
    "snedker": "joiner, carpenter",
    "snige": "to sneak",
    "sti": "path, track",
    "stjæle": "to steal",
    "stolthed": "pride",
    "straffe": "to punish",
    "straks": "immediately",
    "stræde": "strait, alley",
    "stående": "standing",
    "støv": "dust",
    "syning": "sewing",
    "systue": "workroom",
    "sænke": "to lower",
    "tavs": "silent",
    "tavshed": "silence",
    "telt": "tent",
    "tidligere": "earlier",
    "tigge": "to beg",
    "trodsig": "defiant",
    "trosfrihed": "freedom of religion",
    "trække vejret": "to breath",
    "turde": "to dare",
    "tæppe": "blanket",
    "ublodig":"bloodless",
    "ude forbi": "at an end",
    "uden for":"outside",
    "uden om": "around",
    "uden på": "on the cover of",
    "uden tvang": "without coercion",
    "uden tvivl": "without a doubt",
    "uden videre": "just like that, as a matter of course",
    "uden": "without, unless",
    "ugæstfri": "inhospitable",
    "undervisning": "education",
    "uro": "unrest",
    "vare": "to last",
    "vel": "probably",
    "velsignet": "blessed",
    "værksted": "workshop",
    "væv": "tissue, web",
    "væve": "to weave",
    "væver": "weaver, nimble",
    "æsel": "donkey",
    "ørken": "desert",
    "begå": "commit",
    "indrømme": "commit",
    "undgå": "avoid",
    "i stand til": "capable of",
    "tvunget til": "forced to",
    "holdninger": "opinions",
    "afvise": "reject",
    "belaste": "burden",
    "aflaste": "unburden",
    "værdsætte": "appreciate",
    "håndtere": "deal with",
    "styrke": "strength",
    "udvider": "expand",
    "overholder": "comply",
    "tyder på": "indicates",
    "tillid": "confidence, trust",
    "svigte": "betray",
    "træffe": "make (e.g., decision), hit, encounter",
    "afgørende": "significant, important",
    "opfatter": "perceive",
    "tilstand": "condition",
    "feltarbejde": "field work",
    "fornemmelse": "feeling, sense",
    "skelne": "distringuish, discern",
    "tilgang": "approach",
    "funderer": "ponder",
    "værnepligt": "conscript",
    "omsorg": "care",
    "dyder": "virtues",
    "forbundet til": "connection to",
    "efterlyser": "search for",
    "rar": "kind",
    "blikket": "glance",
    "oprethold": "uphold",
    "budskab": "message",
    "fremhæver": "enhance",
    "fofremmelse": "promotion",
    "indføling": "empathy",
    "aer": "stroke",
    "pjece":"leaflet",
    "afskrække":"deter",
    "bort fra": "away from",
    "udnytter": "make use of",
    "hævde": "contend, allege",
    "ildeset": "unwanted, unwelcome",
    "beholde": "keep, retain",
    "afholde": "conduct",
    "optagelse": "admission, enrollment",
    "trænger": "need",
    "genkende": "recognize",
    "udkant": "fringe",
    "udstigning": "exit",
    "indstigning": "entry",
    "færdsel": "traffic",
    "montere": "mount, attach",
    "arter": "species",
    "beskytte": "protect, gaurd",
    "formidling": "arrangement, procurement",
    "beholdning": "supply, stock",
    "efterspørgsel": "demand (for something)",
    "omfatter": "include, incorporate",
    "omtrent": "approximately, more or less",
    "fnisede": "giggled",
    "råbte": "shouted, yelled",
    "knækket": "bent, distorted",
    "kridt": "chalk (for writing)",
    "sagtens": "easily",
    "ernæring": "nutrition",
    "kræsen": "picky, choosy",
    "nogenlunde":"roughly",
    "gennemførte": "completed",
    "lokke": "lure",
    "herkomst": "birth, origin",
    "bukke": "bow down",
    "snavset": "dirty",
    "jævne": "level, even",







};


var phrasesToKnow = {
    "nytter ikke at sige": "pointless to say",
    "det glæder mig": "i would like to",
    "det gør mig glad": "it pleases me",
    "sige op": "resign",
    "slå op": "break up, stop",
    "i løbet af": "during",

};


var statisticsTerms = {
    "gradvist": "gradually",
    "stige støt": "rise steadily",
    "dale støt": "decline steadily",
    "er faldet": "numbers have fallen",
    "først hereafter": "for the first time",
    "stort antal ": "a large number",
    "overgå i antal": "outnumber",
    "samlet antal": "total number",
    "yderligere infomration": "additional information",
    "udviklingen": "increase",
    "faldende brug af": "falling use of",
    "stigende brug af": "rising use of",
    "tælle": "to count",
    
};



var verberForSjov={
    "finde ud af": "find out",
    "finde frem": "discover, identify",
    "finde på": "do, make up (a story)",
    "falde ned": "calm down, fall down (e.g., staircase),",
    "falde om": "drop due to fatigue",
    "falde af": "fall of (e.g., horse)",
    "falde over": "trip over, stumble over",
    "falde ind": "adapt",
    "falde i": "join in, fall in",
    "falde til": "settle down",
    "falde fra": "drop out, fall apart",
    "brænde på": "burnt (e.g., porridge)",
    "brænde ned": "burned down to the ground (e.g., house)",
    "arbejde over": "work overtime",
    "betale af": "pay off (e.g., installments)",
    "blive ved": "continue",
    "gribe an": "to handle",
    "gribe ind": "to intervene",
    "se stort på": "disregard",
    "stort set": "by and large, virtually all",
    "gøre vrovl":"protest",
    "gøre oprør":"protest (political)",
    "gøre en forskel":"make a difference",
    "gøre gavn":"be useful, help",
    "gøre et forsøg":"try one more time",
    "gøre nar ad":"make fun of",
    "gøre grin med":"make fun of (own situation)",
    "gøre om":"start again",
    "lave om": "alter, change (something concrete)",
    "lave af": "made from",
    
};


var forbindelseOrd={
    "for det første/andet": "for the first/second",
    "først": "first",
    "så": "next, consequently",
    "derefter": "thereafter",
    "til sidst": "lastly",
    "enedelig": "finally",
    "bagefter": "afterwards",
    "samtidig med": "simultaneously",
    "ved siden af": "beside",
    "naturaligvis": "naturally",
    "sandsynligvis": "probably",
    "heldigvis": "luckily",
    "desværre": "unfortunately",
    "muligvis": "probably, possibly",
    "måske": "maybe",
    "selvfølgelig": "of course",
    "derfor": "therefore",
    "som følge heraf": "it follows",
    "dvs.": "which means",
    "faktisk": "actually",
    "bagefter": "afterwards",
    "egentlig": "actually",
    "det betyder": "it means",
    "nemlig": "exactly",
    "sagt på en anden måde": "said in another way",
    "altså": "accordingly, really, therefore",
    "omvendt": "vice versa",
    "ligesom": "similarly",
    "dog": "however",
    "mens": "while",
    "alligevel": "anyway, nevertheless, nonetheless",
    "i stedet for": "in place of",
    "derimod": "on the other hand",
    "trods alt": "afterall",
    "af den grund": "for this reason",
    "det skyldes at": "it is because",
    "arsågen hertil er": "reason for this is",
    "kort og godt": "in short",
    "som sagt": "as said",
    "kort sagt": "in summary",
    "generalt set": "in general",
    "eksempelvis": "e.g.",
    "afslutningsvis": "in closing",
    "desuden": "moreover",
    "endvidere": "furthermore",
    "derudover": "in addition",
    "ligeledes": "likewise, also",
    "i øvrigt": "moreover",
    "tværtimod": "on the contrary",
    "dermed": "thus",
    "til gengæld": "however",
    "trods det at": "despite",
    "på trods af": "even though",
    "uanset om": "no matter what",
    "untagen hvis": "except if",
    "foreløbig": "preliminary",
    "imidlertid": "however, still",
    "hverken": "neither",
    "betingelse for": "condition for",
    "såfremt": "in case, as long as",




};