
var dict = {
    "affald": "waste",
    "albue": "elbow, to elbow",
    "altså": "accordingly, really",
    "alvor": "seriousness",
    "alvorlig": "serious, severe",
    "ansvar": "responsibility",
    "barndomshjem": "childhood home",
    "begyndelse": "beginning",
    "bonde": "farmer",
    "bred": "shore, broad, wide",
    "brede ud": "to spread out, to unfold",
    "brede": "to spread",
    "broderi": "embroidery",
    "bunke": "pile",
    "byde": "to offer",
    "bygget": "built",
    "byld": "abscess",
    "bøje": "to bend",
    "bønder": "farmers",
    "dengang": "back then, at that time",
    "deroppe": "up there",
    "det var helt og holdent min skyld": "it was entirely my fault",
    "duft": "fragrance",
    "dufte": "to smell",
    "dygtig": "skilled",
    "dyrke": "to grow",
    "ellers": "otherwise",
    "endnu": "still, yet",
    "ensom": "lonely",
    "erhverv": "occupation",
    "farligt": "dangerous",
    "flyve": "to fly",
    "forelskelse": "infatuation",
    "forfærdelige": "terrible",
    "forklare": "to explain",
    "forsigtigt": "carefully",
    "forskrækket": "frightened",
    "forsvandt": "disappeared",
    "forsørge": "to support, to provide for",
    "forsørger": "breadwinner",
    "fremmed": "foreign",
    "fremmed": "strange",
    "fugtig":"humid",
    "gemme": "to save, to hide",
    "glæde": "joy",
    "gribe an": "to handle (a situation g.. a..)",
    "gribe ind": "to intervene",
    "gribe": "to grip, to catch",
    "græs": "grass",
    "græsse": "to graze",
    "gå i gang": "to start, to begin",
    "gårdsplads": "courtyard",
    "handlende": "tradesman",
    "hellere": "rather, sooner",
    "helskindet": "without a scratch",
    "helst": "preferably, rather",
    "helt": "hero, completely",
    "hidsig": "hot tempered",
    "hoste": "cough",
    "hvad som helst": "anything",
    "hvede": "wheat",
    "hvem som helst": "anybody",
    "hverken": "neither",
    "hvilken som helst": "any",
    "hviske": "to whisper",
    "hvor som helst": "anywhere, wherever",
    "håndtryk": "handshake",
    "håndværk": "profession",
    "høj": "hill",
    "i det lange løb": "in the long run",
    "ifølge": "according to",
    "ildrød": "fiery red",
    "indbyde": "to invite",
    "indbydelse": "invitation",
    "indbygger": "inhabitant",
    "inden for rækkevidde": "within reach",
    "inden for": "within",
    "inden i": "inside",
    "inden under": "underneath",
    "inden": "before",
    "indenom": "along the inside",
    "indenrigs": "domestic",
    "indføre":"to introduce",
    "indre": "interior, inner",
    "indrette": "to organize",
    "ingen som helst": "not at all",
    "intet som helst": "nothing whatsoever",
    "klem": "hug",
    "klippe": "cliff",
    "komme væk": "to get away",
    "kopper": "smallpox",
    "kølig": "cool",
    "landbrug": "agriculture, farming",
    "landskab": "landscape",
    "langt fra": "a long way from, far away from",
    "langt ind i": "far into",
    "langt om længe": "at long last",
    "langt væk": "far away",
    "langtfra": "not at all, far from",
    "langvejs": "a long way",
    "lighed": "equality",
    "læs": "load",
    "løfte:": "to promise, to lift",
    "medfølelse": "compassion",
    "missionær": "missionary",
    "miste": "to lose",
    "mon": "I wonder",
    "må hellere": "better",
    "nikke": "to nod",
    "noget helt andet": "something completely different",
    "når som helst": "whenever, anytime",
    "nødvendigt": "necessary",
    "ophæve":"to repeal",
    "opleve": "to experience",
    "opmærksomt": "carefully",
    "oprør": "rebellion",
    "oven": "on top (o..)",
    "overalt": "everywhere",
    "overfalde": "to assault",
    "overraskede": "surprised",
    "overskrift": "title",
    "pege":"to point",
    "piske": "to whip",
    "plejebarn": "foster child",
    "rask": "healthy",
    "rask": "healthy",
    "regne med": "count on, depend on",
    "regne": "to calculate",
    "regnskab": "account",
    "rejsende": "traveller",
    "ryg": "back",
    "ryg": "back",
    "rygte": "rumor",
    "rynke": "to frown, wrinkle",
    "ryste": "to shake, to upset",
    "række ud": "to reach out",
    "røver": "robber",
    "skab": "cupboard, closet",
    "skomager": "cobbler",
    "skridt": "step",
    "skrædderværksted": "tailor workshop",
    "skygge": "shadow",
    "skynde": "to rush",
    "skælde": "to scold",
    "slags": "type",
    "slette": "plain, field, to delete, to erase",
    "slippe": "to release",
    "smed": "smith",
    "smide": "to throw",
    "snedker": "joiner, carpenter",
    "snige": "to sneak",
    "sti": "path, track",
    "stjæle": "to steal",
    "stolthed": "pride",
    "straffe": "to punish",
    "straks": "immediately",
    "stræde": "strait, alley",
    "stående": "standing",
    "støv": "dust",
    "syning": "sewing",
    "systue": "workroom",
    "sælge": "to sell",
    "sænke": "to lower",
    "tavs": "silent",
    "tavshed": "silence",
    "telt": "tent",
    "tidligere": "earlier",
    "tigge": "to beg",
    "tigge": "to beg",
    "trodsig": "defiant",
    "trosfrihed": "freedom of religion",
    "trække vejret": "to breath",
    "turde": "to dare",
    "tæppe": "blanket",
    "ublodig":"bloodless",
    "ude forbi": "at an end",
    "uden for":"outside",
    "uden om": "around",
    "uden på": "on the cover of",
    "uden tvang": "without coercion",
    "uden tvivl": "without a doubt",
    "uden videre": "just like that, as a matter of course",
    "uden": "without, unless",
    "ugæstfri": "inhospitable",
    "undervisning": "education",
    "uro": "unrest",
    "vare": "to last",
    "vel": "probably",
    "velsigne": "to bless",
    "velsignet": "blessed",
    "værksted": "workshop",
    "væv": "tissue, web",
    "væve": "to weave",
    "væver": "weaver, nimble",
    "væveri": "textile mill",
    "æsel": "donkey",
    "ørken": "desert",
};